version: "3.6"

services:
  app:
    build: ./
    container_name: gradle-app
    volumes:
      - ./:/airtransportationTest
    ports:
      - 8080:8080
    expose:
      - 8080
#    networks:
#      - ktor-network
#    depends_on:
#      - database
#  database:
#    container_name: 172.20.8.18
#    image: postgres:latest
#    environment:
#      - POSTGRES_DB=db0091_05
#      - POSTGRES_USER=st0091
#      - POSTGRES_PASSWORD=qwerty91
#    ports:
#      - 5432:5432
#    expose:
#      - 5432
#    networks:
#      - ktor-network
#networks:
#  ktor-network:
#    driver: bridge